version: '3.1'
services:
    zoneminder:
        container_name: zoneminder
        image: dlandon/zoneminder.machine.learning:latest
        restart: unless-stopped
        ports:
            - 8443:443/tcp
            - 8001:80/tcp
            - 9001:9000/tcp
        network_mode: "bridge"
        privileged: false
        # shm_size: "8gb"
        shm_size: "640MB"

        
        environment:
            - TZ=America/New_York
            - PUID=99
            - PGID=100
            - MULTI_PORT_START=0
            - MULTI_PORT_END=0
        volumes:
            - ./20_apt_update.sh:/etc/my_init.d/20_apt_update.sh
            - config:/config:rw
            - data:/var/cache/zoneminder:rw
volumes:
    config:
    data: