version: '3.1'
services:
    head-body-det:
        image: mehran69/crowd-human-head-body
        # build: ./src
        container_name: head-body-det
        working_dir: /home/head_body_detection_yolov3/
        entrypoint: /home/head_body_detection_yolov3/init.sh
        ports:
        - 8000:8000
        volumes:
        - ./src/:/home/head_body_detection_yolov3/
        tty: true
    postgres: 
        image: postgres
        container_name: postgres_container
        volumes:
        - ./data:/var/lib/postgresql/data
        ports:
        -  5432:5432
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass

